### PR TITLE
fix: files not rendered or contents not substituted when previous list empty

### LINKED ISSUE #1610: fix: files not rendered or contents not substituted when previous list empty
**Description**

Rendering fails if you have two or more list variables and a previous list is empty.

**Steps To Reproduce**

1. Create a brick that uses loops. See [example](https://github.com/felangel/mason/blob/9aa0213d8761f3954154e6ee7b498151095f4787/packages/mason/test/bricks/loop/__brick__/main_%7B%7B%23values%7D%7D%7B%7B%7B.%7D%7D%7D%7B%7B/values%7D%7D.txt)
2. Generate the brick with parameters that include an empty list preceding the list with information to be rendered
```dart
{
  'emptyList': <String>[],
  'values': ['development', 'staging', 'production'],
}
```
3. Files are either not rendered or the contents are not substituted

**Expected Behavior**

List with information should be rendered

### PR DESCRIPTION
**Pull request by jwelmac**
## Status

**READY**

## Description

Fixes #1610

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/mason/lib/src/generator.dart [hunk 1]
```diff
@@ -476,6 +476,7 @@ class TemplateFile {
       }
 
       final fileContents = <FileContents>{};
+      parameters.removeWhere((key, value) => value is List && value.isEmpty);
```
Comment (felangel) [inline packages/mason/lib/src/generator.dart]: Hmm I'm not sure this is correct fix but thanks for contributing and providing a clear test case. I'll take a closer look shortly and try to get this released very soon.

Comment (jwelmac) [reply packages/mason/lib/src/generator.dart]: In my previous [commit](https://github.com/felangel/mason/pull/1611/commits/1eddca3ea1c3e2e922eb3e18d2456c6ef6945b72) I filtered out the values from the lists used for the permutations and parameterKeys.

The issue is generated when the param is being generated on [this line](https://github.com/felangel/mason/pull/1611/files/ccd91a85d8de61ba2face839ee125a161c5cf696#diff-053f4a2bf2a02385445d8facc017ebbbcfe79e7647a3f5fcc51f3e2383821ffbL491) and the parameterKeys and permutations do not align.

Comment (jwelmac) [reply packages/mason/lib/src/generator.dart]: I refactored the initial implementation to prevent having to loop through the map twice to perform the same operation.

Comment (felangel) [reply packages/mason/lib/src/generator.dart]: https://github.com/Khuwn-Soulutions/mason/pull/1

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contribution!

**Comment by felangel** [comment]
Just released mason v0.1.2 which includes this fix 🎉

**Comment by jwelmac** [comment]
Thank you so much.
