### PR TITLE
fix(mason): git brick install across file systems

### LINKED ISSUE #828: fix: FileSystemException on mason get
**Description**

Whenever I run mason get in my project directory, I get this error.
```sh
FileSystemException: Rename failed, path = '/tmp/IPHPMH' (OS Error: Invalid cross-device link, errno = 18)
```

**Steps To Reproduce**

1. run mason init
2. add this to your mason.yaml
```yaml
bricks:
  hello: 0.1.0+1
  annoying_analysis_options: ^0.0.1
  feature_brick: ^0.4.0
  app_ui: ^0.0.4
  heavy_repository_package:
    git:
      url: https://github.com/Prn-Ice/mason_bricks.git
      path: bricks/heavy_repository_package
  heavy_service_package: ^0.0.2
```
4. run mason get
5. See error

**Expected Behavior**

No error.

**Screenshots**

**Additional Context**

Flutter version: 
```sh
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (2 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1
```

OS: Endeavour OS

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Description

- fix(mason): git brick install across file systems (closes #828)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: packages/mason/test/src/generator_test.dart [hunk 1]
```diff
@@ -12,6 +12,10 @@ class _MockLogger extends Mock implements Logger {}
 
 void main() {
   group('MasonGenerator', () {
+    final identicalString = '  ${cyan.wrap('identical')} ';
```
Comment (felangel) [inline packages/mason/test/src/generator_test.dart:15]: These tests were acting a bit flaky so I made them a bit more strict which seemed to help
